import Head from "next/head";
import Banner from "../components/banner/banner.components";
import NavBar from "../components/navbar/navbar.components";
import Card from "../components/card/card.components";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar username="ahmedatif" />
      <Banner
        title="Cliford the red dog"
        subTitle="a very cute dog"
        imgUrl="/static/clifford.webp"
      />

      <Card imgUrl="/static/clifford.webp" size="large" />
      <Card imgUrl="/static/clifford.webp" size="medium" />
      <Card size="small" />

      {/**
  <NavBar/>
  */}
    </div>
  );
}
